# Generated by Django 5.0.6 on 2024-06-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, max_length=20, null=True, verbose_name='Долгота')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Levl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_winter', models.CharField(choices=[('4A', '4A'), ('2A', '2A'), ('1A', '1A'), ('3A', '3A')], default='4A', max_length=2)),
                ('level_spring', models.CharField(choices=[('4A', '4A'), ('2A', '2A'), ('1A', '1A'), ('3A', '3A')], default='4A', max_length=2)),
                ('level_summer', models.CharField(choices=[('4A', '4A'), ('2A', '2A'), ('1A', '1A'), ('3A', '3A')], default='4A', max_length=2)),
                ('level_autumn', models.CharField(choices=[('4A', '4A'), ('2A', '2A'), ('1A', '1A'), ('3A', '3A')], default='4A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Названия припятствия')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вершина')),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другое название')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'информация не принята')], default='new', max_length=10)),
                ('connect', models.TextField(blank=True, null=True)),
                ('coords', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mypereval.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mypereval.levl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mypereval.users')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=125)),
                ('pereval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mypereval.pereval')),
            ],
        ),
    ]
